version: "3"
services:
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: jejugohell
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3305:3306
    restart: always
  application:
    build: .
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3305/jejugohell?characterEncoding=UTF-8&serverTimezone=UCT&ssl=false
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
