spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(6mG0pT8a2dxBJv4L5hToV/7ofaYwgLpXQgvOUUv0xYMcsB0JqHgCqr5c2ZniqHRWkjrdlOrVAVyeosKmMrdd2w6GWeo+AGUhpOoAKAib8cee79zPpZQNcvXlZl8hCEc9wUrurjn675TuUXIOQR1OJxizr9qu7IW2sV/rhjOju0xXdKnclrIv30zbxrsLOqK6)
    username: ENC(tjPEky3f0GKrf2eqQi9pqA==)
    password: ENC(xazzIJDugMtXrRvwgwS6Pg==)
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ENC(PPES3lvb17m9mvU8JFlxjnUkVDCNgXkjnvbW1YNOQ90=)
      secret-key: ENC(IDVyowki7KfcZqsLFbfHA5NdAj3c9+cOkjKyRYJI2d3YoMLsi3uVDKkElmL3Q6HY+FkL8e+T5oE=)
    s3:
      bucket: ENC(G8wjKGi+Cwv0rDog2mlDnnSe9dYKeevD)
    cloudfront:
      domain: ENC(mHsNDiGKA3CGHKxZ3eRUSg1sCAyufggfn5nX72liHKcqSzlQHjw5DqBlDPVn4LEE)

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}